name: Release Build & Publish

on:
  push:
    tags:
      - 'v*'        # publish semantic-version tags like v1.2.3
      - '*'         # also allow other tag names if you prefer (optional)

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install deps
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Run tests
        run: |
          if [ -f pytest.ini ] || ls **/*test*.py 1> /dev/null 2>&1; then
            pip install pytest
            pytest -q
          else
            echo "No tests detected, skipping."
          fi

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest
